### ISSUE TITLE
node-blink1-server in docker container?

### ISSUE THREAD

**Issue by DennisGaida** [todbot/node-blink1-server#14]
Anyone got the node server working running in a docker container?

I always fail at building the node-hid module and I have tried running a debian container as well as a alpine container.

My current dockerfile (that doesn't work) is:
```
FROM debian:bullseye-slim

RUN apt update
RUN apt -y -q install build-essential git pkg-config libudev-dev libusb-1.0-0 libusb-1.0-0-dev
RUN apt -y -q install python3 npm
RUN npm install -g node-blink1-server
```
The error is always about node-hid:
```
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/node-blink1-server/node_modules/node-hid
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild
npm ERR! make: Entering directory '/usr/local/lib/node_modules/node-blink1-server/node_modules/node-hid/build'
npm ERR!   CC(target) Release/obj.target/hidapi/hidapi/libusb/hid.o
npm ERR!   AR(target) Release/obj.target/hidapi.a
npm ERR!   COPY Release/hidapi.a
npm ERR!   CXX(target) Release/obj.target/HID/src/HID.o
npm ERR! make: Leaving directory '/usr/local/lib/node_modules/node-blink1-server/node_modules/node-hid/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@12.22.5 | linux | arm
npm ERR! gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/share/nodejs/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/node-blink1-server/node_modules/node-hid/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/share/nodejs/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/include/nodejs/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/share/nodejs/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/usr/include/nodejs/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/local/lib/node_modules/node-blink1-server/node_modules/node-hid',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
...
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:6126:46: note: candidate: 'v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)'
npm ERR!  6126 |   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
npm ERR!       |                                              ^~~~~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:6126:46: note:   candidate expects 1 argument, 0 provided
npm ERR! In file included from ../src/HID.cc:30:
npm ERR! ../src/HID.cc: At global scope:
npm ERR! /usr/include/nodejs/src/node.h:736:7: warning: cast between incompatible function types from 'void (*)(v8::Local<v8::Object>)' to 'node::addon_register_func' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)'} [-Wcast-function-type]
npm ERR!   736 |       (node::addon_register_func) (regfunc),                          \
npm ERR!       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! /usr/include/nodejs/src/node.h:770:3: note: in expansion of macro 'NODE_MODULE_X'
npm ERR!   770 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
npm ERR!       |   ^~~~~~~~~~~~~
npm ERR! ../src/HID.cc:629:3: note: in expansion of macro 'NODE_MODULE'
npm ERR!   629 |   NODE_MODULE(HID, init);
npm ERR!       |   ^~~~~~~~~~~
npm ERR! make: *** [HID.target.mk:118: Release/obj.target/HID/src/HID.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/share/nodejs/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
npm ERR! gyp ERR! System Linux 5.10.63-v7l+
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/share/nodejs/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /usr/local/lib/node_modules/node-blink1-server/node_modules/node-hid
npm ERR! gyp ERR! node -v v12.22.5
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
```
But I **am** able to install node-hid globally:
```
# npm install node-hid -g

added 61 packages, and audited 62 packages in 12s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by DennisGaida** [comment]
Maybe this helps someone in the future: Needs to use very old node version.

Working `dockerfile`:
```
FROM arm32v7/node:8.16.1-alpine 

# add usb basics
RUN apk add --update --quiet libusb libusb-dev eudev-dev
# add build environment
RUN apk add --no-cache --virtual .gyp python2 make g++ linux-headers

# install blink1-server
RUN npm config set user root
RUN npm install --silent -g node-blink1-server
# cleanup
RUN apk del --quiet .gyp && rm -rf /var/cache/apk

EXPOSE 8080

ENTRYPOINT ["blink1-server", "8080"]
```
